http:
  port: "8081"
  path: "users"
db:
  mySql:
    host: "localhost"
    user: "root"
    password: "![KDJFnCGOFqU=]"
    port: "3306"
  oracle:
    host: "localhost"
    user: "root"
    password: "root"
    port: "3306"